name: encore2_gamesheet
description: A (digital) game sheet for Bravo (Noch Mal so gut / Keer op Keer 2)

publish_to: "none" 

version: 1.1.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  assets_audio_player: ^3.0.5
  wakelock_plus: ^1.2.8
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf